Repository DioxusLabs/docsite, pull requests merged in 2024-12, with the labels that each got.

#327 Add a 0.6 migration guide
  assets/githubmarkdown.css
  assets/main.css
  docs-src/0.5/src/migration/fermi.md
  docs-src/0.5/src/migration/hooks.md
  docs-src/0.5/src/migration/index.md
  docs-src/0.5/src/migration/props.md
  docs-src/0.5/src/migration/state.md
  docs-src/0.6/src/SUMMARY.md
  docs-src/0.6/src/migration/index.md
  src/doc_examples/migration.rs
  src/doc_examples/untested_05/migration.rs
  src/doc_examples/untested_05/migration_fermi.rs
  src/doc_examples/untested_05/migration_hooks.rs
  src/doc_examples/untested_05/migration_props.rs
  src/doc_examples/untested_05/migration_state.rs
  src/docs/router_06.rs
Labels: documentation

#330 Move registering server functions to a wasm specific note
  docs-src/0.5/src/reference/fullstack/server_functions.md
  docs-src/0.6/src/reference/fullstack/server_functions.md
Labels: documentation, fullstack

#336 Improve Search Styling
  README.md
  assets/tailwind.css
  docs-src/0.4/en/cookbook/integrations/internationalization.md
  docs-src/0.5/src/cookbook/integrations/internationalization.md
  docs-src/0.6/src/cookbook/integrations/internationalization.md
  src/components/nav.rs
  src/doc_examples/untested_05/i18n.rs
  src/docs/router_03.rs
  src/docs/router_04.rs
  src/docs/router_05.rs
  src/docs/router_06.rs
  src/docs/router_blog.rs
Labels: enhancement

#331 Add documentation about managing dependencies in dioxus fullstack
  docs-src/0.6/src/SUMMARY.md
  docs-src/0.6/src/guides/fullstack/managing_dependencies.md
  src/doc_examples/server_tokio_import.rs
  src/docs/router_06.rs
Labels: documentation, enhancement, fullstack

#342 Update documentation links to Dioxus 0.6
  README.md
  docs-src/0.6/src/CLI/translate.md
  docs-src/0.6/src/SUMMARY.md
  docs-src/0.6/src/contributing/index.md
  docs-src/0.6/src/contributing/walkthrough_readme.md
  docs-src/0.6/src/cookbook/optimizing.md
  docs-src/0.6/src/guides/desktop/index.md
  docs-src/0.6/src/guides/mobile/apis.md
  docs-src/0.6/src/guides/ssr.md
  docs-src/0.6/src/reference/router.md
  docs-src/0.6/src/router/example/index.md
  docs-src/0.6/src/router/index.md
  src/components/footer.rs
  src/components/homepage.rs
  src/components/homepage/hero.rs
  src/components/learn.rs
  src/components/nav.rs
  src/components/playground.rs
  src/docs.rs
  src/docs/router_06.rs
Labels: bug, documentation

#361 Fix route for Routing Guide
  docs-src/0.6/src/guide/routing.md
Labels: bug, documentation
