Repository DioxusLabs/docsite, pull requests merged in 2025-02, with the labels that each got.

#406 Fix search index generation
  .github/workflows/gh-pages.yml
  Cargo.toml
  src/components/nav.rs
  src/components/search.rs
  src/main.rs
Labels: bug

#394 Add documentation about setting up and building ssg
  assets/06_docs/ssg_folder.png
  docs-src/0.6/src/SUMMARY.md
  docs-src/0.6/src/guides/fullstack/static_site_generation.md
  src/doc_examples/static_site_generation.rs
Labels: documentation, fullstack

#402 Async/Suspense essentials guide
  assets/06_docs/streaming_dogs.mp4
  assets/main.css
  docs-src/0.6/src/SUMMARY.md
  docs-src/0.6/src/essentials/async/index.md
  docs-src/0.6/src/essentials/index.md
  src/doc_examples/asynchronous.rs
  src/doc_examples/mod.rs
Labels: documentation, enhancement

#412 Revision: Playground CSS
  .github/workflows/gh-pages.yml
  packages/docsite/src/components/homepage/snippets.rs
  packages/docsite/src/components/nav.rs
  packages/include_mdbook/packages/mdbook-gen/src/rsx.rs
  packages/playground/playground/assets/dxp.css
  packages/playground/playground/src/components/header.rs
  packages/playground/playground/src/components/icons.rs
  packages/playground/playground/src/editor/monaco.js
  packages/playground/playground/src/lib.rs
Labels: enhancement, playground

#427 Fix: Playground Run Button Background
  packages/playground/playground/assets/dxp.css
Labels: playground

#429 Fix: Playground
  docs-src/0.4/en/contributing/walkthrough_readme.md
  docs-src/0.6/src/index.md
  packages/docsite/src/components/playground.rs
  packages/playground/runner/src/main.rs
Labels: playground

#437 Improve error handling guide
  docs-src/0.6/src/SUMMARY.md
  docs-src/0.6/src/cookbook/error_handling.md
  docs-src/0.6/src/cookbook/index.md
  docs-src/0.6/src/essentials/error_handling/index.md
  docs-src/0.6/src/essentials/index.md
  docs-src/0.6/src/reference/hooks.md
  packages/docs-router/src/doc_examples/error_handling.rs
  packages/docs-router/src/doc_examples/mod.rs
  packages/docs-router/src/docs.rs
  packages/docs-router/src/lib.rs
  packages/docsite/src/docs.rs
  packages/include_mdbook/packages/mdbook-gen/src/rsx.rs
  packages/playground/playground/src/components/icons.rs
  packages/playground/playground/src/lib.rs
Labels: documentation, enhancement

#440 Fix include statements that are not at the start of a codeblock
  packages/include_mdbook/packages/mdbook-gen/src/rsx.rs
Labels: bug

#443 Fix very long words in search index
  Cargo.lock
  Cargo.toml
  packages/docs-router/Cargo.toml
  packages/docsite/Cargo.toml
  packages/docsite/src/components/nav.rs
  packages/docsite/src/components/search.rs
  packages/search/search-shared/Cargo.toml
  packages/search/search-shared/src/lib.rs
  packages/search/search/Cargo.toml
Labels: bug
